name: Scan Image

on:
  workflow_dispatch:
  schedule:
    - cron: '15 23 * * *'

jobs:
  check-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Image Name
        run: |
          export IMAGE=$(./build.sh -p | sed "s/\.[0-9a-z-]*$//")
          echo "IMAGE=${IMAGE}-php83-node" >> $GITHUB_ENV

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Run trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "MEDIUM,HIGH,CRITICAL"
        env:
          TRIVY_DB_REPOSITORY: aquasec/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: aquasec/trivy-java-db:1
  
      - name: Try to start build workflow if trivy failed
        if: ${{ failure() }}
        run: |
          curl -X POST -u ${{ secrets.PAT }} -H "Accept: application/vnd.github.v3+json" -d '{"ref":"refs/heads/master"}' https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/build.yml/dispatches
